// FENCO 2.0 — Shared Type Definitions

export type DocumentType = 'freelance' | 'residential_lease' | 'other';
export type DocumentStatus = 'uploaded' | 'ingesting' | 'ingested' | 'analyzing' | 'analyzed' | 'error';
export type RiskLevel = 'Standard' | 'Caution' | 'Unfavorable';
export type MessageRole = 'user' | 'assistant';
export type MoreFavorable = 'document_a' | 'document_b' | 'neither' | 'depends';
export type SourceType = 'public_legal_aid' | 'bar_association_template' | 'synthetic_llm_generated' | 'public_domain_form' | 'other';

export interface Document {
  id: string;
  filename: string;
  originalName: string;
  documentType: DocumentType;
  status: DocumentStatus;
  errorMessage?: string;
  reducedAccuracyMode: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Clause {
  id: string;
  documentId: string;
  clauseIndex: number;
  clauseType: string;
  text: string;
  embedding?: number[];
  riskLevel?: RiskLevel;
  similarityScore?: number;
  confidenceScore?: number;
  usedFallbackEmbedding: boolean;
  usedFallbackLlmModel?: string;
  semanticDeltaExplanation?: string;
  counterDraft?: string;
  counterDraftExplanation?: string;
  topBenchmarkMatchId?: string;
  stage1Only: boolean;
  createdAt: Date;
}

export interface BenchmarkClause {
  id: string;
  clauseType: string;
  documentType: DocumentType;
  text: string;
  embedding?: number[];
  sourceAttribution: string;
  sourceType: SourceType;
  sourceUrlOrNote: string;
  lastReviewedAt?: Date;
  createdAt: Date;
}

export interface ScoredClause {
  id: string;
  clauseIndex: number;
  clauseType: string;
  text: string;
  riskLevel: RiskLevel;
  similarityScore: number;
  confidenceScore: number;
  usedFallbackEmbedding: boolean;
  usedFallbackLlmModel?: string;
  semanticDeltaExplanation: string;
  counterDraft?: string;
  counterDraftExplanation?: string;
  stage1Only: boolean;
}

export interface Gotcha {
  title: string;
  explanation: string;
  riskLevel: RiskLevel;
  relatedClauseIndex: number;
}

export interface AnalysisResult {
  documentId: string;
  documentType: DocumentType;
  reducedAccuracyMode: boolean;
  summary: {
    total: number;
    standard: number;
    caution: number;
    unfavorable: number;
    stage1SavedCount: number; // clauses resolved without LLM
  };
  clauses: ScoredClause[];
  gotchas: Gotcha[];
  disclaimer: string;
}

export interface QaSession {
  id: string;
  documentId: string;
  createdAt: Date;
}

export interface QaMessage {
  id: string;
  sessionId: string;
  role: MessageRole;
  content: string;
  relatedClauseIds: string[];
  createdAt: Date;
}

export interface QaAnswer {
  sessionId: string;
  messageId: string;
  answer: string;
  relatedClauseIds: string[];
  disclaimer: string;
}

export interface ComparisonClausePair {
  id: string;
  comparisonId: string;
  clauseA?: Clause;
  clauseB?: Clause;
  clauseType: string;
  differenceExplanation?: string;
  moreFavorable?: MoreFavorable;
  onlyInDocument?: 'document_a' | 'document_b';
}

export interface ComparisonResult {
  id: string;
  documentAId: string;
  documentBId: string;
  summary: string;
  matchedPairs: ComparisonClausePair[];
  onlyInDocumentA: ComparisonClausePair[];
  onlyInDocumentB: ComparisonClausePair[];
  disclaimer: string;
  createdAt: Date;
}

export interface AttorneyChecklistItem {
  clauseIndex: number;
  clauseType: string;
  riskLevel: RiskLevel;
  whyItMatters: string;
  questionsToAsk: string[];
  documentsToGather: string[];
}

export interface AttorneyChecklist {
  summary: string;
  flaggedItems: AttorneyChecklistItem[];
  disclaimer: string;
}

export interface EmbeddingResult {
  embedding: number[];
  usedFallback: boolean;
  model: string;
}

export interface LlmCallResult {
  content: string;
  model: string;
  usedFallback: boolean;
}

export const LEGAL_DISCLAIMER = 'IMPORTANT: This analysis is generated by AI and is provided for informational purposes only. It does not constitute legal advice and should not be relied upon as such. Every contract situation is unique, involving jurisdiction-specific laws, relationship dynamics, and negotiation context that AI cannot fully assess. Please consult a licensed attorney before signing any contract or making legal decisions.';
