// FENCO 2.0 — Benchmark Corpus Seeder
// Provider: Google Gemini (via @google/genai) for embeddings
// Embedding model: gemini-embedding-001 (3072 dims)
// Last verified: 2026-09-22
//
// All benchmark clauses are labeled synthetic_llm_generated.
// See BENCHMARK_PROVENANCE.md for full provenance explanation.

import { getPool, withTransaction, closePool } from './connection';
import { getEnv } from '../config/env';
import { hashText, generateFallbackEmbedding } from '../utils/index';

interface BenchmarkClauseSeed {
  clauseType: string;
  documentType: 'freelance' | 'residential_lease';
  text: string;
  sourceAttribution: string;
  sourceUrlOrNote: string;
}

const BENCHMARK_CLAUSES: BenchmarkClauseSeed[] = [
  // ============ FREELANCE AGREEMENTS ============
  {
    clauseType: 'Payment Terms',
    documentType: 'freelance',
    text: 'Client shall pay Contractor the agreed fee within thirty (30) days of invoice receipt. Late payments shall accrue interest at 1.5% per month on the outstanding balance. Client shall reimburse all pre-approved expenses within fifteen (15) days of submission.',
    sourceAttribution: 'Standard freelance payment terms - synthetic',
    sourceUrlOrNote: 'Synthetic clause generated by Gemini 3.8 Flash and reviewed for commercial reasonableness. Reflects common net-30 payment practice with standard late-fee provisions.',
  },
  {
    clauseType: 'Scope of Work',
    documentType: 'freelance',
    text: 'Contractor shall perform the services described in Schedule A attached hereto. Any additional work beyond the defined scope must be agreed to in writing by both parties before Contractor begins such work, and shall be compensated at Contractor\'s standard hourly rate or as otherwise mutually agreed.',
    sourceAttribution: 'Standard scope of work clause - synthetic',
    sourceUrlOrNote: 'Synthetic clause reflecting balanced scope-control protections. Requires written consent for scope expansion, protecting both parties.',
  },
  {
    clauseType: 'Intellectual Property',
    documentType: 'freelance',
    text: 'Upon receipt of full payment, Contractor assigns to Client all copyright and intellectual property rights in the deliverables specifically created for this engagement. Contractor retains ownership of all pre-existing tools, frameworks, and methodologies used in creating the deliverables, and grants Client a perpetual, non-exclusive license to use such pre-existing IP as incorporated in the deliverables.',
    sourceAttribution: 'Balanced IP assignment clause - synthetic',
    sourceUrlOrNote: 'Synthetic clause that represents a balanced IP allocation: client owns the custom work product, contractor retains pre-existing IP with a use license. Commonly negotiated form.',
  },
  {
    clauseType: 'Confidentiality',
    documentType: 'freelance',
    text: 'Each party agrees to maintain the confidentiality of the other party\'s proprietary information and trade secrets for a period of two (2) years following completion of the engagement. Obligations do not apply to information that is publicly available, independently developed, or required to be disclosed by law.',
    sourceAttribution: 'Mutual NDA clause - synthetic',
    sourceUrlOrNote: 'Synthetic mutual confidentiality clause with standard carve-outs. Two-year term and mutual obligations reflect balanced approach.',
  },
  {
    clauseType: 'Indemnification',
    documentType: 'freelance',
    text: 'Each party shall indemnify and hold harmless the other party from claims arising from that party\'s own negligence, willful misconduct, or material breach of this Agreement. Neither party shall be obligated to indemnify the other for claims caused by the indemnified party\'s own actions or omissions.',
    sourceAttribution: 'Mutual indemnification clause - synthetic',
    sourceUrlOrNote: 'Synthetic mutual indemnification with causation linkage. Each party is responsible for their own negligence only, which is the balanced standard form.',
  },
  {
    clauseType: 'Limitation of Liability',
    documentType: 'freelance',
    text: 'In no event shall either party be liable to the other for indirect, incidental, consequential, or punitive damages. Each party\'s total liability under this Agreement shall not exceed the total fees paid or payable to Contractor in the three (3) months preceding the claim.',
    sourceAttribution: 'Mutual limitation of liability - synthetic',
    sourceUrlOrNote: 'Synthetic mutual limitation clause. Cap at 3-month fees is a common and balanced negotiated outcome for freelance contracts.',
  },
  {
    clauseType: 'Termination',
    documentType: 'freelance',
    text: 'Either party may terminate this Agreement for cause upon fifteen (15) days written notice if the other party materially breaches and fails to cure within the notice period. Either party may terminate for convenience upon thirty (30) days written notice. Upon termination, Client shall pay for all work completed and approved through the termination date.',
    sourceAttribution: 'Balanced termination clause - synthetic',
    sourceUrlOrNote: 'Synthetic termination clause with both for-cause and for-convenience rights, plus pro-rata payment protection. Represents balanced approach.',
  },
  {
    clauseType: 'Dispute Resolution',
    documentType: 'freelance',
    text: 'The parties agree to first attempt to resolve any dispute through good-faith negotiation for thirty (30) days. If unresolved, disputes shall be submitted to binding arbitration under the rules of the American Arbitration Association, with costs shared equally. Either party may seek emergency injunctive relief from a court of competent jurisdiction.',
    sourceAttribution: 'Arbitration clause with cost-sharing - synthetic',
    sourceUrlOrNote: 'Synthetic dispute resolution clause. Equal cost-sharing and emergency injunction carve-out are balanced provisions.',
  },
  {
    clauseType: 'Governing Law',
    documentType: 'freelance',
    text: 'This Agreement shall be governed by the laws of the State of [STATE], without regard to its conflict of laws provisions. The parties consent to the exclusive jurisdiction of the courts of [STATE] for any matters not subject to arbitration.',
    sourceAttribution: 'Standard governing law clause - synthetic',
    sourceUrlOrNote: 'Synthetic governing law placeholder. Neutral form — state should be negotiated to be mutually convenient.',
  },
  {
    clauseType: 'Non-Compete',
    documentType: 'freelance',
    text: 'During the term of this Agreement, Contractor agrees not to solicit Client\'s direct employees for competing engagements. This Agreement shall not restrict Contractor\'s ability to perform similar services for other clients, including competitors of Client, unless separately agreed in a written non-compete addendum.',
    sourceAttribution: 'Narrow non-solicitation - synthetic',
    sourceUrlOrNote: 'Synthetic narrow non-solicitation clause. Restricts only direct employee poaching, not competitive work. Represents contractor-protective balanced form.',
  },
  {
    clauseType: 'Insurance',
    documentType: 'freelance',
    text: 'Contractor shall maintain professional liability (errors & omissions) insurance of at least $500,000 per occurrence during the term of this Agreement and shall provide Client with a certificate of insurance upon request.',
    sourceAttribution: 'Professional liability insurance requirement - synthetic',
    sourceUrlOrNote: 'Synthetic insurance clause with reasonable E&O coverage requirement. $500K per occurrence is a common minimum for knowledge-work freelancers.',
  },
  {
    clauseType: 'Amendments',
    documentType: 'freelance',
    text: 'This Agreement may only be amended by a written instrument signed by authorized representatives of both parties. No oral modifications or course of conduct shall be deemed to amend this Agreement.',
    sourceAttribution: 'Standard amendments clause - synthetic',
    sourceUrlOrNote: 'Synthetic amendments clause. Written-only requirement protects both parties from informal modification disputes.',
  },
  {
    clauseType: 'Force Majeure',
    documentType: 'freelance',
    text: 'Neither party shall be liable for delay or failure caused by events beyond their reasonable control, including natural disasters, government actions, or service provider outages, provided the affected party gives prompt written notice and uses reasonable efforts to mitigate. Force majeure does not excuse payment obligations for work already completed.',
    sourceAttribution: 'Force majeure with payment carve-out - synthetic',
    sourceUrlOrNote: 'Synthetic force majeure clause with payment carve-out. Protects both parties while ensuring completed work is still paid.',
  },
  {
    clauseType: 'Warranty',
    documentType: 'freelance',
    text: 'Contractor warrants that the deliverables will materially conform to the specifications in Schedule A for sixty (60) days following delivery. Contractor\'s sole obligation under this warranty is to correct non-conforming work at no additional charge. EXCEPT AS EXPRESSLY STATED, DELIVERABLES ARE PROVIDED AS-IS WITHOUT WARRANTIES OF MERCHANTABILITY OR FITNESS.',
    sourceAttribution: 'Limited warranty clause - synthetic',
    sourceUrlOrNote: 'Synthetic limited warranty with 60-day cure period. Disclaimer of implied warranties is standard commercial practice.',
  },
  {
    clauseType: 'Assignment',
    documentType: 'freelance',
    text: 'Neither party may assign this Agreement or any rights hereunder without the prior written consent of the other party, except that Client may assign to a successor entity in a merger or acquisition. Any purported assignment without consent shall be void.',
    sourceAttribution: 'Mutual assignment restriction - synthetic',
    sourceUrlOrNote: 'Synthetic mutual assignment restriction with M&A carve-out for client. Protects contractor from being assigned to an unknown entity.',
  },
  {
    clauseType: 'Notice',
    documentType: 'freelance',
    text: 'All notices under this Agreement shall be in writing and delivered by email (with read receipt or delivery confirmation) or certified mail to the addresses specified in this Agreement. Email notice is effective upon confirmed delivery.',
    sourceAttribution: 'Notice clause with email - synthetic',
    sourceUrlOrNote: 'Synthetic notice clause allowing email as valid notice method, which is practical for modern freelance relationships.',
  },

  // ============ RESIDENTIAL LEASES ============
  {
    clauseType: 'Payment Terms',
    documentType: 'residential_lease',
    text: 'Rent of $[AMOUNT] per month is due on the first day of each month. A grace period of five (5) days applies before late fees are assessed. Late fees shall not exceed 5% of the monthly rent or the maximum permitted by applicable state law, whichever is lower.',
    sourceAttribution: 'Standard residential rent payment - synthetic',
    sourceUrlOrNote: 'Synthetic lease payment clause with 5-day grace period and capped late fees. These are common tenant-protective provisions.',
  },
  {
    clauseType: 'Security Deposit',
    documentType: 'residential_lease',
    text: 'Landlord may collect a security deposit not to exceed two (2) months\' rent. The deposit shall be held in a separate interest-bearing account and returned within thirty (30) days of lease termination, with an itemized written statement of any deductions for damages beyond normal wear and tear.',
    sourceAttribution: 'Security deposit with tenant protections - synthetic',
    sourceUrlOrNote: 'Synthetic security deposit clause. Itemization requirement and wear-and-tear exclusion are standard tenant protections. Return period reflects common state law minimums.',
  },
  {
    clauseType: 'Maintenance and Repairs',
    documentType: 'residential_lease',
    text: 'Landlord shall maintain the premises in habitable condition and promptly repair systems essential to health and safety (heating, plumbing, electrical) within seventy-two (72) hours of written notice. Tenant shall notify Landlord in writing of needed repairs and is responsible for damages caused by Tenant\'s negligence.',
    sourceAttribution: 'Habitability maintenance clause - synthetic',
    sourceUrlOrNote: 'Synthetic maintenance clause with habitability standard and reasonable repair timeline. Reflects implied warranty of habitability requirements.',
  },
  {
    clauseType: 'Termination',
    documentType: 'residential_lease',
    text: 'Landlord may terminate this lease for nonpayment of rent upon thirty (30) days written notice. Either party may terminate at the natural expiration of the lease term upon sixty (60) days prior written notice. Early termination by Tenant requires sixty (60) days notice and payment of two (2) months\' rent as liquidated damages, unless Landlord finds a qualified replacement tenant sooner.',
    sourceAttribution: 'Balanced lease termination - synthetic',
    sourceUrlOrNote: 'Synthetic termination clause with proportionate early-termination penalty and mitigation obligation.',
  },
  {
    clauseType: 'Entry and Privacy',
    documentType: 'residential_lease',
    text: 'Landlord shall provide at least twenty-four (24) hours written notice before entering the premises, except in genuine emergencies. Landlord\'s right of entry is limited to inspection, repairs, and showing to prospective tenants within sixty (60) days of lease expiration.',
    sourceAttribution: 'Tenant privacy / notice of entry - synthetic',
    sourceUrlOrNote: 'Synthetic entry clause with 24-hour notice and scope limitations. Reflects most states\' statutory minimum notice requirements.',
  },
  {
    clauseType: 'Indemnification',
    documentType: 'residential_lease',
    text: 'Landlord shall indemnify Tenant from claims arising from Landlord\'s negligence or failure to maintain habitable conditions. Tenant shall indemnify Landlord from claims arising from Tenant\'s negligence or intentional acts. Neither party\'s indemnification obligation extends to the other party\'s own negligence.',
    sourceAttribution: 'Mutual residential lease indemnification - synthetic',
    sourceUrlOrNote: 'Synthetic mutual indemnification clause. Explicitly excludes cross-indemnification for own negligence, which is the balanced standard.',
  },
  {
    clauseType: 'Subletting',
    documentType: 'residential_lease',
    text: 'Tenant may not sublet the premises without Landlord\'s prior written consent, which shall not be unreasonably withheld or delayed. Landlord shall respond to any written subletting request within fifteen (15) days.',
    sourceAttribution: 'Subletting with reasonableness standard - synthetic',
    sourceUrlOrNote: 'Synthetic subletting clause with reasonableness standard and response deadline. Protects tenant from arbitrary denial.',
  },
  {
    clauseType: 'Pets',
    documentType: 'residential_lease',
    text: 'No pets are permitted without Landlord\'s prior written consent. If pets are permitted, an additional refundable pet deposit of $[AMOUNT] may be charged, not to exceed the statutory maximum. Service animals and emotional support animals are permitted as required by law without additional deposit.',
    sourceAttribution: 'Pet clause with ADA/FHA compliance - synthetic',
    sourceUrlOrNote: 'Synthetic pet clause with legally required service/ESA carve-out per FHA and ADA.',
  },
  {
    clauseType: 'Dispute Resolution',
    documentType: 'residential_lease',
    text: 'The parties agree to attempt good-faith mediation before initiating legal proceedings for disputes under $[AMOUNT]. Either party may pursue claims in small claims court without first mediating. Nothing herein prevents either party from seeking emergency relief for imminent harm.',
    sourceAttribution: 'Mediation-first residential lease dispute clause - synthetic',
    sourceUrlOrNote: 'Synthetic dispute resolution with small-claims and emergency carve-outs. Mediation-first is common tenant-protective provision.',
  },
  {
    clauseType: 'Governing Law',
    documentType: 'residential_lease',
    text: 'This lease shall be governed by the laws of [STATE], including applicable landlord-tenant statutes. Any provision of this lease that conflicts with applicable law is void and severable without affecting the remaining provisions.',
    sourceAttribution: 'Residential lease governing law - synthetic',
    sourceUrlOrNote: 'Synthetic governing law with statutory compliance and severability. Placeholder state to be filled by user.',
  },
  {
    clauseType: 'Renewal',
    documentType: 'residential_lease',
    text: 'This lease shall convert to a month-to-month tenancy at the same rent upon expiration unless either party provides sixty (60) days written notice of non-renewal. Landlord may increase rent upon sixty (60) days written notice, subject to any applicable rent control regulations.',
    sourceAttribution: 'Lease renewal / holdover clause - synthetic',
    sourceUrlOrNote: 'Synthetic renewal clause with notice requirements and rent control compliance language.',
  },
  {
    clauseType: 'Utilities',
    documentType: 'residential_lease',
    text: 'Landlord shall provide and pay for: [LIST]. Tenant is responsible for: [LIST]. Landlord shall not disconnect or interrupt any service used or needed by Tenant as a means of enforcing any provision of this lease.',
    sourceAttribution: 'Utilities clause with lockout prohibition - synthetic',
    sourceUrlOrNote: 'Synthetic utilities clause with anti-lockout provision per most state landlord-tenant statutes.',
  },
  {
    clauseType: 'Notice',
    documentType: 'residential_lease',
    text: 'All notices required under this lease shall be in writing and delivered by personal service, certified mail return receipt requested, or email with confirmed delivery to the addresses listed in this agreement. Notice is effective upon confirmed receipt.',
    sourceAttribution: 'Residential lease notice clause - synthetic',
    sourceUrlOrNote: 'Synthetic notice clause with multiple delivery methods and effectiveness on receipt.',
  },
  {
    clauseType: 'Force Majeure',
    documentType: 'residential_lease',
    text: 'If the premises become uninhabitable due to casualty beyond either party\'s control, Tenant\'s rent obligation is suspended for the period of uninhabitability. Landlord shall use reasonable efforts to restore habitability within sixty (60) days or Tenant may terminate the lease without penalty.',
    sourceAttribution: 'Residential force majeure with rent suspension - synthetic',
    sourceUrlOrNote: 'Synthetic casualty/force majeure clause with rent abatement and termination right. Reflects implied warranty of habitability standards.',
  },
  {
    clauseType: 'Insurance',
    documentType: 'residential_lease',
    text: 'Tenant is encouraged to maintain renter\'s insurance for personal property. Landlord\'s insurance does not cover Tenant\'s personal belongings. Landlord shall maintain property insurance on the structure and liability insurance of at least $1,000,000.',
    sourceAttribution: 'Residential insurance disclosure clause - synthetic',
    sourceUrlOrNote: 'Synthetic insurance clause. Landlord liability coverage requirement and clear disclosure of what is/is not covered.',
  },
  {
    clauseType: 'Alterations',
    documentType: 'residential_lease',
    text: 'Tenant may not make alterations, improvements, or installations without Landlord\'s prior written consent. Approved alterations become part of the premises unless Landlord requests removal in writing. Minor decorative changes (hanging pictures, temporary fixtures) require no approval.',
    sourceAttribution: 'Alterations clause with carve-out - synthetic',
    sourceUrlOrNote: 'Synthetic alterations clause with minor-decoration carve-out. Reasonable for residential context.',
  },
  {
    clauseType: 'Assignment',
    documentType: 'residential_lease',
    text: 'Tenant may not assign this lease without Landlord\'s prior written consent, not to be unreasonably withheld. Landlord shall respond to assignment requests within ten (10) business days. Assignment with consent does not release Tenant from liability unless Landlord expressly agrees in writing.',
    sourceAttribution: 'Residential lease assignment clause - synthetic',
    sourceUrlOrNote: 'Synthetic assignment clause with reasonableness standard and response deadline.',
  },
];

async function seedBenchmarkClauses(): Promise<void> {
  const env = getEnv();
  const pool = getPool();
  
  console.log('🌱 Starting benchmark clause seeder...');
  console.log(`   Embedding model: ${env.EMBEDDING_PRIMARY_MODEL}`);
  console.log(`   Total clauses to check: ${BENCHMARK_CLAUSES.length}`);
  
  // Check which clauses already exist (by hash)
  const hashes = BENCHMARK_CLAUSES.map(c => hashText(c.text));
  const existingResult = await pool.query(
    'SELECT text_hash FROM benchmark_clauses WHERE text_hash = ANY($1)',
    [hashes]
  );
  const existingHashes = new Set(existingResult.rows.map((r: { text_hash: string }) => r.text_hash));
  
  const newClauses = BENCHMARK_CLAUSES.filter(c => !existingHashes.has(hashText(c.text)));
  console.log(`   Already seeded: ${BENCHMARK_CLAUSES.length - newClauses.length}`);
  console.log(`   New clauses to embed and insert: ${newClauses.length}`);
  
  if (newClauses.length === 0) {
    console.log('✅ Seeder: nothing to do, all clauses already present.');
    return;
  }
  
  // Embed all new clauses in one batch call
  // For seeding, we use a simple approach without the full embeddingService
  // to avoid circular dependency issues at seed time
  let embeddings: number[][];
  let usedFallback = false;
  
  try {
    const { GoogleGenAI } = await import('@google/genai');
    const ai = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });
    
    console.log(`   Embedding ${newClauses.length} clauses via ${env.EMBEDDING_PRIMARY_MODEL}...`);
    embeddings = [];
    
    // Batch in groups of 5 to respect rate limits
    for (let i = 0; i < newClauses.length; i += 5) {
      const batch = newClauses.slice(i, i + 5);
      const batchEmbeddings = await Promise.all(
        batch.map(async (clause) => {
          const result = await ai.models.embedContent({
            model: env.EMBEDDING_PRIMARY_MODEL,
            contents: clause.text,
            config: { outputDimensionality: env.EMBEDDING_DIMENSIONS },
          });
          return result.embeddings?.[0]?.values ?? [];
        })
      );
      embeddings.push(...batchEmbeddings);
      
      if (i + 5 < newClauses.length) {
        await new Promise(resolve => setTimeout(resolve, 500)); // rate limit pause
      }
    }
    
    console.log(`   ✅ Embeddings generated via ${env.EMBEDDING_PRIMARY_MODEL}`);
  } catch (err) {
    console.warn(`   ⚠️  Embedding failed, using fallback vectors: ${err instanceof Error ? err.message : String(err)}`);
    usedFallback = true;
    embeddings = newClauses.map(c => generateFallbackEmbedding(c.text, env.EMBEDDING_DIMENSIONS));
  }
  
  // Insert all new clauses in a single transaction
  await withTransaction(async (client) => {
    for (let i = 0; i < newClauses.length; i++) {
      const clause = newClauses[i];
      const embedding = embeddings[i];
      const hash = hashText(clause.text);
      
      await client.query(
        `INSERT INTO benchmark_clauses 
          (clause_type, document_type, text, text_hash, embedding, 
           source_attribution, source_type, source_url_or_note, last_reviewed_at)
         VALUES ($1, $2, $3, $4, $5::vector, $6, $7, $8, NOW())
         ON CONFLICT (text_hash) DO NOTHING`,
        [
          clause.clauseType,
          clause.documentType,
          clause.text,
          hash,
          `[${embedding.join(',')}]`,
          clause.sourceAttribution,
          'synthetic_llm_generated', // ALL benchmark clauses are honest about this
          clause.sourceUrlOrNote,
        ]
      );
    }
  });
  
  if (usedFallback) {
    console.warn('   ⚠️  Seeded with fallback embeddings. Re-run seeder with a valid GEMINI_API_KEY for accurate embeddings.');
  }
  
  console.log(`✅ Seeder complete. Inserted ${newClauses.length} new benchmark clauses.`);
}

seedBenchmarkClauses()
  .catch(err => {
    console.error('❌ Seeder failed:', err.message);
    process.exit(1);
  })
  .finally(() => closePool());
